#!/bin/sh

BRANCH=$(git rev-parse --abbrev-ref HEAD)
REGEX="^([a-zA-Z0-9\-]+)(\/[a-zA-Z0-9._-]+)$"

echo "test"

if ! [[ $BRANCH =~ $REGEX ]]; then
  echo "Your commit was rejected due to branching name"
  echo "Please rename your branch with '<username>/<branch_name>' syntax"
  exit 1
fi
